### ISSUE TITLE
Virtual Machines (WSL, Docker, ..) do not support PyQT6 (for the PyXAI's GUI)

### ISSUE THREAD

**Issue by szczepanskiNicolas** [crillab/pyxai#6]
Under Windows by simulating Ubuntu with WSL : 

`import pyxai`

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicolas/pyxai/pyxai/__init__.py", line 8, in <module>
    from pyxai.sources.core.tools.GUIQT import GraphicalInterface
  File "/home/nicolas/pyxai/pyxai/sources/core/tools/GUIQT.py", line 3, in <module>
    from PyQt6.QtWidgets import QSplitter, QApplication, QAbstractItemView, QHeaderView, QBoxLayout, QFrame, QMessageBox, QFileDialog, QLabel, QSizePolicy, QScrollArea,  QStyleFactory, QMainWindow, QTableWidgetItem, QHBoxLayout, QMenu, QGroupBox, QListWidget, QWidget, QVBoxLayout, QGridLayout, QTableWidget
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory
```

A solution for deactivating the GUI during installation and import is currently being implemented. 

Meanwhile, for imports:

Solution from [Here](https://forum.qt.io/topic/136058/libqt6core-so-6-cannot-open-shared-object-file-even-though-it-exists-seems-to-depend-on-docker-host-os)

`LD_DEBUG=libs python3` allows us to locate the library. 

`cd /home/nicolas/.local/lib/python3.10/site-packages/PyQt6/Qt6/lib`

`strip --remove-section=.note.ABI-tag libQt6Core.so.6`

Now `import pyxai` will works but a new problem appear with `python3 -m pyxai`:

```
qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
qt.core.library: "/home/nicolas/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" cannot load: Cannot load library /home/nicolas/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6: undefined symbol: _ZNK21QPlatformBackingStore9toTextureERK7QRegionP5QSizeP6QFlagsINS_11TextureFlagEE, version Qt_6_PRIVATE_API)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/home/nicolas/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so" : "Cannot load library /home/nicolas/.local/lib/python3.10/site-packages/PyQt6/Qt6/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6: undefined symbol: _ZNK21QPlatformBackingStore9toTextureERK7QRegionP5QSizeP6QFlagsINS_11TextureFlagEE, version Qt_6_PRIVATE_API)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)
```

**Comment by szczepanskiNicolas** [comment]
Solved in the [v1.0.10](https://github.com/crillab/pyxai/releases/tag/v1.0.10).
To resolve compatibility issues with PyQt6, since V1.0.10, PyXAI’s Graphical Interface is independent and no longer mandatory.
